title: Guardian
paginate: 5
theme: "PaperMod"

params:
    title: Guardian
    description: "A friendly, feature-rich moderation tool for Discord servers."
    keywords: [Guardian, Discord, Bot, Moderation]
    author: Cooper Sullivan
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: false
    images: ["papermod-cover.png"]

    assets:
        # disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        favicon: "images/guardian.png"
        favicon16x16: "images/guardian-16.png"
        favicon32x32: "images/guardian-32.png"
        apple_touch_icon: "images/guardian.png"
        safari_pinned_tab: "images/guardian.png"

    label:
        text: "Guardian"
        icon: favicon.svg
        iconHeight: 24

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Guardian
        subtitle: "A friendly, feature-rich moderation tool for Discord servers."
        imageUrl: "images/guardian-zoomout.png"
        imageWidth: 240
        imageHeight: 240
        imageTitle: Guardian
        buttons:
            - name: Documentation
              url: docs/
            - name: Invite
              url: https://discord.com/api/oauth2/authorize?client_id=885618073904767008&permissions=8&scope=bot
    
    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/coopersully/guardian.coopersully.me/tree/main/content"
        Text: "Suggest Changes"
        appendFilePath: true

menu:
    main:
        - identifier: home
          name: home
          url: /
          weight: 10
        - identifier: documentation
          name: documentation
          url: /docs/
          weight: 20
        - identifier: categories
          name: categories
          url: /categories/
          weight: 30
        - identifier: tags
          name: tags
          url: /tags/
          weight: 40
        - identifier: search
          name: search
          url: /search/
          weight: 50
          
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
